name: 'Terraform'
 
on:
  push:
    branches:
    - main
 
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    environment: dev
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.2

    - name: 'Terraform Init'
      id: init
      run: terraform -chdir=terraform init 

    - name: 'Terraform validate'
      id: validate
      run: terraform -chdir=terraform validate 

    - name: 'Terraform plan'
      id: plan
      run: terraform -chdir=terraform plan -out=tfplan

    - name: 'Terraform apply'
      id: apply
      run: terraform -chdir=terraform apply tfplan
